# Generated by Django 4.1.7 on 2023-02-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською')),
                ('title_en', models.CharField(max_length=100, verbose_name='Назва (англійською')),
                ('disabled', models.BooleanField(default=False, verbose_name='Відключено')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Номер за порядком')),
                ('fp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flatpages.flatpage', verbose_name='flat page')),
            ],
            options={
                'verbose_name': 'Пункт основного меню',
                'verbose_name_plural': 'Пункти основного меню',
                'ordering': ['order'],
            },
        ),
    ]
