# Generated by Django 4.1.7 on 2023-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmenu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва (українською)'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='title_en',
            field=models.CharField(max_length=100, verbose_name='Назва (англійською)'),
        ),
    ]
