# Generated by Django 4.1.7 on 2023-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0002_alter_topmenu_title_alter_topmenu_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (англійською)')),
                ('logo', models.FileField(upload_to='media', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ['id'],
            },
        ),
    ]
