# Generated by Django 4.1.7 on 2023-02-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0004_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners', verbose_name='Логотип'),
        ),
    ]
