# Generated by Django 4.1.7 on 2023-02-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('reua', '0005_alter_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (англійською)')),
                ('icon', models.CharField(choices=[('fa-solid fa-file-invoice', 'Текст'), ('fa-solid fa-file-pdf', 'PDF'), ('fa-solid fa-link', 'Посилання')], max_length=50, verbose_name='Іконка')),
                ('fp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flatpages.flatpage', verbose_name='flat page')),
            ],
            options={
                'verbose_name': 'Установчий документ',
                'verbose_name_plural': 'Установчі документи',
                'ordering': ['id'],
            },
        ),
    ]
