# Generated by Django 4.1.7 on 2023-02-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0007_foundingdocument_file_alter_foundingdocument_fp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundingdocument',
            name='icon',
        ),
        migrations.AddField(
            model_name='foundingdocument',
            name='kind',
            field=models.CharField(choices=[('text', 'Текст'), ('pdf', 'PDF'), ('link', 'Посилання')], default='text', max_length=50, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundingdocument',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))], verbose_name='Файл (pdf)'),
        ),
    ]
