# Generated by Django 4.1.7 on 2023-02-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('reua', '0009_companycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenu',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Сторінка FlatPage'), (2, 'Стандартна сторінка')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topmenu',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва стандартної сторінки'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='fp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flatpages.flatpage', verbose_name='flat page'),
        ),
    ]
