# Generated by Django 4.1.7 on 2023-02-23 13:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0010_topmenu_kind_topmenu_url_name_alter_topmenu_fp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('logotype', models.ImageField(blank=True, default=None, null=True, upload_to='company', verbose_name='Логотип')),
                ('descr', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Місто')),
                ('addr', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Адреса')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UA', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-Mail')),
                ('site', models.URLField(blank=True, default=None, null=True, verbose_name='Сайт')),
                ('repr_fio', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('repr_status', models.PositiveSmallIntegerField(choices=[(1, 'Засновник'), (2, 'Директор'), (3, 'Керівник'), (4, 'Менеджер')], verbose_name='Статус представника')),
                ('repr_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UA', verbose_name='Телефон представника')),
                ('repr_email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-Mail представника')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reua.companycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
                'ordering': ['id'],
            },
        ),
    ]
