# Generated by Django 4.1.7 on 2023-02-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('reua', '0011_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_add_code', models.CharField(max_length=20, verbose_name='Код додавання компанії в групу компаній')),
                ('invest_add_code', models.CharField(max_length=20, verbose_name='Код додавання компанії в інвестиції')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
