# Generated by Django 4.1.7 on 2023-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0013_investitioncompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я та прізвище (укр)")),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name="Ім'я та прізвище (англ)")),
                ('position', models.CharField(max_length=100, verbose_name='Посада (укр)')),
                ('position_en', models.CharField(blank=True, max_length=100, verbose_name='Посада (англ)')),
                ('descriprion', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('descriprion_en', models.TextField(blank=True, verbose_name='Опис (англ)')),
                ('photo', models.ImageField(upload_to='staff', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
            },
        ),
    ]
