# Generated by Django 4.1.7 on 2023-02-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0014_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('id',), 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),

    ]
