# Generated by Django 4.1.7 on 2023-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0015_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнери'},
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер за порядком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.RunSQL('update reua_partner set "order"=id')
    ]
