# Generated by Django 4.1.7 on 2023-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0016_alter_partner_options_partner_order_partner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('order',), 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AddField(
            model_name='staff',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер за порядком'),
            preserve_default=False,
        ),
        migrations.RunSQL('update reua_staff set "order"=id', reverse_sql=migrations.RunSQL.noop)
    ]
