# Generated by Django 4.1.7 on 2023-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0019_label_company_labels_investitioncompany_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (англійською)')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Номер за порядком')),
            ],
            options={
                'verbose_name': 'Установка очищення води',
                'verbose_name_plural': 'Установки очищення води',
                'ordering': ['order'],
            },
        ),
    ]
