# Generated by Django 4.1.7 on 2023-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0020_waterstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterstation',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Опис (українською)'),
        ),
        migrations.AddField(
            model_name='waterstation',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Опис (англійською)'),
        ),
    ]
