# Generated by Django 4.1.7 on 2023-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0021_waterstation_desc_waterstation_desc_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'ReH2O'), (2, 'ReCity')], verbose_name='Тип')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (англійською)')),
                ('short_desc', models.TextField(blank=True, verbose_name='Короткий опис (українською)')),
                ('short_desc_en', models.TextField(blank=True, verbose_name='Короткий опис (англійською)')),
                ('desc', models.TextField(blank=True, verbose_name='Детальний опис (українською)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Детальний опис (англійською)')),
                ('target', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='Потрібно')),
                ('current', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='Зібрано')),
                ('closed', models.BooleanField(blank=True, default=False, verbose_name='Завершено')),
                ('currency', models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('UAH', '₴')], default='USD', max_length=3, verbose_name='Валюта')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('image', models.ImageField(blank=True, upload_to='porjects')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['order'],
            },
        ),
    ]
