# Generated by Django 4.1.7 on 2023-03-06 15:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0022_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='addr',
            field=models.TextField(blank=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='addr_en',
            field=models.TextField(blank=True, verbose_name='Адреса англійською'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UA', verbose_name='Телефон'),
        ),
    ]
