# Generated by Django 4.1.7 on 2023-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0023_sitesettings_addr_sitesettings_addr_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='labels',
            field=models.ManyToManyField(blank=True, to='reua.label', verbose_name='Мітки'),
        ),
        migrations.AlterField(
            model_name='investitioncompany',
            name='labels',
            field=models.ManyToManyField(blank=True, to='reua.label', verbose_name='Мітки'),
        ),
    ]
