# Generated by Django 4.1.7 on 2023-03-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0024_alter_company_labels_alter_investitioncompany_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Назва (англійською)')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=999999)),
            ],
            options={
                'verbose_name': 'Категорія інвестицый',
                'verbose_name_plural': 'Категорії інвестицый',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='companycategory',
            options={'ordering': ['order'], 'verbose_name': 'Категорія компаній', 'verbose_name_plural': 'Категорії компаній'},
        ),
        migrations.AddField(
            model_name='companycategory',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=999999),
        ),
        migrations.RunSQL("""
        insert into reua_investitioncategory (title, "order") values 
        ("Промисловiсть", 1), 
        ("Переробка сировини",2), 
        ("Переробка продуктiв",3), 
        ("Логістичний центр",4), 
        ("Промышленные предприятия (создание и реконструкция)",5)
        """, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL("update reua_investitioncompany set category_id=1", reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='investitioncompany',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reua.investitioncategory', verbose_name='Категорія'),
        ),
    ]
