# Generated by Django 4.1.7 on 2023-03-09 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0025_investitioncategory_alter_companycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investitioncompany',
            name='business_plan',
            field=models.FileField(blank=True, help_text='Якщо є', upload_to='documents\\plan', verbose_name='Бізнес план'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='feasibility_study',
            field=models.FileField(blank=True, help_text='Якщо є', upload_to='documents\teo', verbose_name='Техніко-економічне обґрунтування'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Діючий бізнес'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=13, verbose_name='Сума необхідних інвестицій, USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='turnover_1',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='Оборот за попередній рік, грн'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='turnover_2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='Оборот за рік - 2, грн'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='turnover_3',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=13, verbose_name='Оборот за рік - 3, грн'),
        ),
        migrations.AlterField(
            model_name='investitioncompany',
            name='descr',
            field=models.TextField(blank=True, default='', verbose_name='Короткий опис проєкту'),
        ),
    ]
