# Generated by Django 4.1.7 on 2023-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0026_investitioncompany_business_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investitioncompany',
            name='business_plan',
            field=models.FileField(blank=True, help_text='Якщо є', upload_to='documents/plan', verbose_name='Бізнес план'),
        ),
        migrations.AlterField(
            model_name='investitioncompany',
            name='feasibility_study',
            field=models.FileField(blank=True, help_text='Якщо є', upload_to='documents/teo', verbose_name='Техніко-економічне обґрунтування'),
        ),
    ]
