# Generated by Django 4.1.7 on 2023-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0027_alter_investitioncompany_business_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investitioncompany',
            name='quant_of_persons',
            field=models.PositiveSmallIntegerField(default=0, help_text='Кількість співробітників що залучені, або планується залучити', verbose_name='Кількість співробітників'),
            preserve_default=False,
        ),
    ]
