# Generated by Django 4.1.7 on 2023-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0028_investitioncompany_quant_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investitioncompany',
            name='turnover_1',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=13, null=True, verbose_name='Оборот за попередній рік, грн'),
        ),
        migrations.AlterField(
            model_name='investitioncompany',
            name='turnover_2',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=13, null=True, verbose_name='Оборот за рік - 2, грн'),
        ),
        migrations.AlterField(
            model_name='investitioncompany',
            name='turnover_3',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=13, null=True, verbose_name='Оборот за рік - 3, грн'),
        ),
    ]
