# Generated by Django 4.1.7 on 2023-03-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0029_alter_investitioncompany_turnover_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок (українською)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Заголовок (англійською)')),
                ('sub_title', models.TextField(blank=True, verbose_name='Підзаголовок (українською)')),
                ('sub_title_en', models.TextField(blank=True, verbose_name='Підзаголовок (англійською)')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='news/%Y', verbose_name='Основне зображення')),
                ('body', models.TextField(blank=True, verbose_name='Зміст (українською')),
                ('body_en', models.TextField(blank=True, verbose_name='Зміст (англійською)')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (українською)')),
                ('title_en', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Назва (англійською)')),
            ],
            options={
                'verbose_name': 'Категорія новин',
                'verbose_name_plural': 'Категорії новин',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок (українською)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Заголовок (англійською)')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='news/%Y', verbose_name='Зображення')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reua.news', verbose_name='Новина')),
            ],
            options={
                'verbose_name': 'Зображення новин',
                'verbose_name_plural': 'Зображення новин',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reua.newscategory', verbose_name='Категорія новин'),
        ),
    ]
