# Generated by Django 4.1.7 on 2023-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0034_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addr_en',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Адреса (англ.)'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Місто (англ.)'),
        ),
        migrations.AddField(
            model_name='company',
            name='descr_en',
            field=models.TextField(blank=True, default='', verbose_name='Опис (англ.)'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Назва компанії (англ.)'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='addr_en',
            field=models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Адреса (англ.)'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='city_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Місто (англ.)'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='descr_en',
            field=models.TextField(blank=True, default='', verbose_name='Опис (англ.)'),
        ),
        migrations.AddField(
            model_name='investitioncompany',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Назва компанії (англ.)'),
        ),
    ]
