# Generated by Django 4.1.7 on 2023-03-26 16:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0035_company_addr_en_company_city_en_company_descr_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ('date',),
            },
        ),
    ]
