# Generated by Django 4.1.7 on 2023-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0036_feedbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубліковано'),
        ),
    ]
