# Generated by Django 4.2 on 2023-04-10 12:02

from django.db import migrations, models
from pytils.translit import slugify


def fill_slug(apps, schema_editor):
    News = apps.get_model("reua", "News")
    db_alias = schema_editor.connection.alias
    for n in News.objects.using(db_alias).all():
        n.slug = slugify(n.title)
        n.save()



class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0037_news_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
        migrations.RunPython(fill_slug, reverse_code=migrations.RunPython.noop)
    ]
