# Generated by Django 4.2 on 2023-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0038_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
