# Generated by Django 4.2 on 2023-06-15 12:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0039_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UA', verbose_name='Телефон'),
        ),
    ]
