# Generated by Django 4.2.3 on 2023-11-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('reua', '0041_reh2ovideos_reh2osettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reh2ovideos',
            options={'ordering': ('order',), 'verbose_name': 'Відео', 'verbose_name_plural': 'Відео'},
        ),
        migrations.AddField(
            model_name='reh2ovideos',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sites.site', verbose_name='Сайт'),
            preserve_default=False,
        ),
    ]
