# Generated by Django 4.2.3 on 2023-11-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0042_alter_reh2ovideos_options_reh2ovideos_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='for1',
            field=models.CharField(default='for', max_length=1, verbose_name='Для кого'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='for_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='project',
            name='for_city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='project',
            name='for_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='project',
            name='for_region_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Для кого'),
        ),
    ]
