# Generated by Django 4.2.3 on 2023-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0043_project_for1_project_for_city_project_for_city_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='for1',
            field=models.CharField(choices=[('for_city', 'Для міста'), ('for', 'Для')], max_length=8, verbose_name='Для кого'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва населеного пунку'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва населеного пунку (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва області'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_region_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва області (англ.)'),
        ),
    ]
