# Generated by Django 4.2.3 on 2023-11-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0045_activepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prj_photo', verbose_name='Фото')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reua.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Фото проєкту',
                'verbose_name_plural': 'Фото проєктів',
            },
        ),
    ]
