# Generated by Django 4.2.3 on 2023-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0046_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.TextField(blank=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_en',
            field=models.TextField(blank=True, verbose_name='Статус (англ.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва населеного пункту'),
        ),
        migrations.AlterField(
            model_name='project',
            name='for_city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва населеного пункту (англ.)'),
        ),
    ]
