# Generated by Django 4.2.3 on 2023-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0050_alter_reh2ovideos_video_alter_reh2ovideos_video_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='reh2ovideos',
            name='poster',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='posters', verbose_name='Постер'),
        ),
    ]
