# Generated by Django 4.2.7 on 2023-11-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0051_reh2ovideos_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenu',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reua.topmenu', verbose_name='Батьківський пункт меню'),
        ),
    ]
