# Generated by Django 4.2.7 on 2023-12-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0052_topmenu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmenu',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='reua.topmenu', verbose_name='Батьківський пункт меню'),
        ),
        migrations.CreateModel(
            name='BankTransferAttributesStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('attrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='reua.banktransferattributes', verbose_name='Банківські реквізити')),
            ],
            options={
                'verbose_name': 'Строка реквізитів',
                'verbose_name_plural': 'Строки реквізитів',
            },
        ),
    ]
