# Generated by Django 4.2.7 on 2023-12-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0053_alter_topmenu_parent_banktransferattributesstrings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransferattributes',
            name='attr_en',
        ),
    ]
