# Generated by Django 4.2.7 on 2023-12-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0054_remove_banktransferattributes_attr_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferattributesstrings',
            name='header',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
