# Generated by Django 4.2.7 on 2023-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0055_alter_banktransferattributesstrings_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reCity_text',
            field=models.TextField(blank=True, verbose_name='Текст призначення для ReCity'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reCity_text_en',
            field=models.TextField(blank=True, verbose_name='Текст призначення для ReCity'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reh2o_text',
            field=models.TextField(blank=True, verbose_name='Текст призначення для ReH2O'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reh2o_text_en',
            field=models.TextField(blank=True, verbose_name='Текст призначення для ReH2O'),
        ),
    ]
