# Generated by Django 4.2.7 on 2023-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0057_alter_sitesettings_recity_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransferattributes',
            name='attr',
        ),
    ]
