# Generated by Django 4.2.7 on 2023-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0058_remove_banktransferattributes_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='current',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_desc_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target',
        ),
        migrations.AddField(
            model_name='project',
            name='desc1',
            field=models.TextField(blank=True, verbose_name='Детальний опис (українською)'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_en1',
            field=models.TextField(blank=True, verbose_name='Детальний опис (англійською)'),
        ),
    ]
