# Generated by Django 4.2.7 on 2023-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0059_remove_project_currency_remove_project_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc_en',
        ),
    ]
