# Generated by Django 4.2.7 on 2023-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reua', '0060_remove_project_desc_remove_project_desc_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desc_en1',
            new_name='desc_en',
        ),
    ]
