"""
Django settings for reua2 project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

from django.templatetags.static import static
from django.utils.functional import SimpleLazyObject

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8zlf=bhbz(g&kgooj54-!a)frqp*6)q218-wvmlhd!ug*&gxxd'

# SECURITY WARNING: don't run with debug turned on in production!
try:
    from .override_settings import DEBUG
except ImportError:
    DEBUG = False

try:
    from .override_settings import ALLOWED_HOSTS
except ImportError:
    ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.flatpages',
    'reua.apps.ReuaConfig',
    'phonenumber_field',
    'fontawesomefree',
    'sorl.thumbnail',
    'django_filters',
    'django_summernote',
    'adminsortable',
    'captcha',
]

MIDDLEWARE = [
    'reua.middlewares.locale.RemoveLocaleFromRequest',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reua2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reua.context_processors.top_menus'
            ],
        },
    },
]

WSGI_APPLICATION = 'reua2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGES = [
    ('uk', "UA"),
    ('en', "EN"),
    # ('ru', "RU"),
]

LANGUAGE_CODE = 'uk'

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale'), ]

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  #

if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT, mode=0o755, exist_ok=True)

STATICFILES_DIRS = (MEDIA_ROOT,)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

######### LOGS #########################
LOG_ROOT = os.path.join(BASE_DIR, 'log')
if not os.path.exists(LOG_ROOT):
    os.makedirs(LOG_ROOT, mode=0o755, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format':
                '{levelname} {asctime} {module} {message}',
            'style':
                '{',
        },
    },
    'handlers': {
        'application': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_ROOT, 'application.log'),
            'formatter': 'verbose',
        },
        'db': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_ROOT, 'db.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['application'],
            'propagate': True,
            'level': 'ERROR',
        },
        'django.request': {
            'handlers': ['application'],
            'level': 'DEBUG',
        },
        'django.db.backends': {
            'level': 'DEBUG',
            # 'level': 'INFO',
            'handlers': ['db'],
        },
    }
}

CSRF_TRUSTED_ORIGINS = ['https://reua.com.ua']

PHONENUMBER_DEFAULT_REGION = 'UA'

SITE_ID = 1

USE_THOUSAND_SEPARATOR = True

try:
    from .override_settings import GMAP_API_KEY
except ImportError:
    GMAP_API_KEY = None

try:
    from .override_settings import TELEGRAM_TOKEN, TELEGRAM_CHAT_ID
except ImportError:
    TELEGRAM_TOKEN = TELEGRAM_CHAT_ID = None

try:
    from .override_settings import GOOGLE_DATA_STREAM_ID
except ImportError:
    GOOGLE_DATA_STREAM_ID = None

from .summernote_config import *

PAYMENT_CRYPTO_RE_H2O = 'https://reua.pay.whitepay.com/'
PAYMENT_CRYPTO_RE_CITY = 'https://rebuildua.pay.whitepay.com/'

PAYMENT_CARD_RE_H2O = {
    "UAH": 'https://patronizerbot.com/@reua_city_voda_uah',
    "USD": 'https://patronizerbot.com/@reua_city_voda_usd',
    "EUR": 'https://patronizerbot.com/@reua_city_voda_eur',
}

PAYMENT_CARD_RE_CITY = {
    "UAH": 'https://patronizerbot.com/@reua_city_bud_uah',
    "USD": 'https://patronizerbot.com/@reua_city_bud_usd',
    "EUR": 'https://patronizerbot.com/@reua_city_bud_eur',
}

TMP_ROOT = os.path.join(BASE_DIR, 'tmp')  #

if not os.path.exists(TMP_ROOT):
    os.makedirs(TMP_ROOT, mode=0o755, exist_ok=True)

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = TMP_ROOT

try:
    from .email_settings import *
except:
    pass



CAPTCHA_IMAGE_SIZE = 160, 60
CAPTCHA_FONT_SIZE = 44
CAPTCHA_2X_IMAGE = False
